name: docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip build]')"
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push images
        id: docker_build
        uses: docker/build-push-action@v2.4.0
        with:
          push: true
          tags: revelacio/dtspolimdo:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    steps:
      -
        name: Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH2_HOST}}
          username: ${{ secrets.SSH2_USERNAME }}
          password: ${{ secrets.SSH2_PASSWORD }}
          port: ${{ secrets.SSH2_PORT}}
          no-cache: true
          script: |
            "./deploy/dtspolimdo.sh"